#!/bin/bash


echo "Bienvenue dans ce script d'install"
echo "Thx pour avoir dl mon script"
echo
echo
echo "Tous les scripts sont situes dans ~/.push"
read -p "Quel shell utilisez vous : " shell
if [ $shell != "bash" ] && [ $shell != "zsh" ];then
    echo "Je connais pas ce shell sry"
    exit
fi
shell=${shell}rc
if [ -d ~/.push ]; then
    echo "Veuillez supprimer le dossier ~/.push"
    exit 1
fi
if cat $HOME/.$shell | grep "## PUSH SCRIPT ##"; then
    echo "Merci de supprimer dans .$shell les lignes du scripts, afin que nous refassions une installation propre"
    exit
fi
chmod +x *
read -p "Alias pour le push: " push
mkdir ~/.push
cp n.py $HOME/.push/
cp my_recu $HOME/.push/
cp push $HOME/.push/$push
echo "Alias pour Mr. Clean : mrc"
cp mr_clean $HOME/.push/mrc
echo "Alias pour clone un rep : clone"
cp clone $HOME/.push/clone
echo "Alias pour prepare un repo : prepare"
cp prepare_my_repo $HOME/.push/prepare
echo "Copie des fichiers termines"
echo "Attribution des droits termines"
echo  >> $HOME/.$shell
echo "## PUSH SCRIPT ## Pls don't touch this" >> $HOME/.$shell
echo 'export PATH="$HOME/.push:$PATH"' >> $HOME/.$shell
chmod +x $HOME/.push/mouli
echo  >> $HOME/.$shell
echo "Modification du path termines"
echo "Restart du terminal"
echo
echo "Installation termine gg et ty"
echo
